# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "linode-letsencrypt-dns01-hooks-unstable-${version}";
  version = "2017-06-12";
  rev = "6f185036fe879c9f820cecfc488e0b35a8400714";

  goPackagePath = "github.com/IdeaSynthesis/letsencrypt-dns01-hooks";

  src = fetchFromGitHub {
    inherit rev;
    owner = "IdeaSynthesis";
    repo = "letsencrypt-dns01-hooks";
    sha256 = "0ffnk49dmpni63gjm8rb295h3skbqhjbzzgkj1cfcllzwkqaqa6n";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    description = "Linode DNS provider hooks for the dehydrated script's dns01 ACME challenge";
    homepage = https://github.com/IdeaSynthesis/letsencrypt-dns01-hooks;
    license = with licenses; [ bsd3 ];
    maintainers = with maintainers; [ ryantm ];
    platforms = platforms.unix;
  };
}
