# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/miekg/dns";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/dns";
      rev = "906238edc6eb0ddface4a1923f6d41ef2a5ca59b";
      sha256 = "169gwgq9i3g1b9vm6nrqd74n9j78g4gf475qshc188n79mblysaf";
    };
  }
]
